language: go
go:
  - "1.10.x"

services:
  - docker

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test ./...
  - docker build --pull --tag "strider2038/message-router" .
  - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
  - docker push strider2038/message-router
