// Code generated by MockGen. DO NOT EDIT.
// Source: KafkaWriter.go

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	kafka_go "github.com/segmentio/kafka-go"
	reflect "reflect"
)

// MockKafkaWriter is a mock of KafkaWriter interface
type MockKafkaWriter struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaWriterMockRecorder
}

// MockKafkaWriterMockRecorder is the mock recorder for MockKafkaWriter
type MockKafkaWriterMockRecorder struct {
	mock *MockKafkaWriter
}

// NewMockKafkaWriter creates a new mock instance
func NewMockKafkaWriter(ctrl *gomock.Controller) *MockKafkaWriter {
	mock := &MockKafkaWriter{ctrl: ctrl}
	mock.recorder = &MockKafkaWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKafkaWriter) EXPECT() *MockKafkaWriterMockRecorder {
	return m.recorder
}

// WriteMessages mocks base method
func (m *MockKafkaWriter) WriteMessages(ctx context.Context, msgs ...kafka_go.Message) error {
	varargs := []interface{}{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages
func (mr *MockKafkaWriterMockRecorder) WriteMessages(ctx interface{}, msgs ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockKafkaWriter)(nil).WriteMessages), varargs...)
}
